AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudWatch: alarma CPU > umbral con SNS (email)."

Parameters:
  InstanceId:
    Type: String
    Description: "EC2 InstanceId."
  AlertEmail:
    Type: String
    Description: "Email para alertas (requiere confirmación)."
  CpuThreshold:
    Type: Number
    Default: "80"           # <= como string
    Description: "Umbral de CPU (%)."
  PeriodSeconds:
    Type: Number
    Default: "300"          # <= como string
    AllowedValues: ["60","120","300","600","900"]   # <= todos como string
    Description: "Periodo (s)."
  EvaluationPeriods:
    Type: Number
    Default: "1"            # <= como string
    Description: "Cantidad de periodos."
  TopicName:
    Type: String
    Default: ""             # <= sin !Sub; vacío = nombre auto
    Description: "Opcional: si vacío, AWS auto-nombra el tópico."

Conditions:
  HasTopicName: !Not [!Equals [!Ref TopicName, ""]]

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !If [HasTopicName, !Ref TopicName, !Ref "AWS::NoValue"]

  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  HighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub "CPU > ${CpuThreshold}% (${PeriodSeconds}s)"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceId
      Statistic: Average
      Unit: Percent
      Period: !Ref PeriodSeconds
      EvaluationPeriods: !Ref EvaluationPeriods
      Threshold: !Ref CpuThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions: [ !Ref AlarmTopic ]
      OKActions:    [ !Ref AlarmTopic ]

Outputs:
  TopicArn:   { Value: !Ref AlarmTopic }
  AlarmName:  { Value: !Ref HighCpuAlarm }
