AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudWatch: alarma CPU > umbral con SNS (email)."

Parameters:
  InstanceId:
    Type: String
    Description: "InstanceId al que se le aplica la alarma."
  AlertEmail:
    Type: String
    Description: "Email para recibir alertas (requiere confirmar suscripción)."
  CpuThreshold:
    Type: Number
    Default: "80"
    Description: "Umbral de CPU (%) para disparar la alarma."
  PeriodSeconds:
    Type: Number
    Default: "300"
    AllowedValues: [60, 120, 300, 600, 900]
    Description: "Periodo de evaluación en segundos."
  EvaluationPeriods:
    Type: Number
    Default: "1"
    MinValue: 1
    Description: "Cantidad de periodos para evaluar."
  TopicName:
    Type: String
    Default: !Sub "${AWS::StackName}-alerts"
    Description: "Nombre del tópico SNS."

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  HighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-cpu-gt${CpuThreshold}"
      AlarmDescription: !Sub "CPU > ${CpuThreshold}% (${PeriodSeconds}s)"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: InstanceId
          Value: !Ref InstanceId
      Statistic: Average
      Unit: Percent
      Period: !Ref PeriodSeconds
      EvaluationPeriods: !Ref EvaluationPeriods
      DatapointsToAlarm: !Ref EvaluationPeriods
      Threshold: !Ref CpuThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions: [ !Ref AlarmTopic ]
      OKActions:    [ !Ref AlarmTopic ]

Outputs:
  TopicArn:
    Value: !Ref AlarmTopic
  AlarmName:
    Value: !Ref HighCpuAlarm
