AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM: optional programmatic user with minimal S3 access."

Parameters:
  S3BucketName:
    Type: String
    Description: "Bucket name for RW access."
  CreateProgrammaticUser:
    Type: String
    AllowedValues: ["true","false"]
    Default: "true"
  CreateAccessKey:
    Type: String
    AllowedValues: ["true","false"]
    Default: "true"

Conditions:
  DoCreateUser: !Equals [!Ref CreateProgrammaticUser, "true"]
  DoCreateKey:  !And [!Condition DoCreateUser, !Equals [!Ref CreateAccessKey, "true"]]
  HasBucket:    !Not [!Equals [!Ref S3BucketName, ""]]

Resources:
  S3RWPolicy:
    Condition: HasBucket
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-s3rw"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3RW
            Effect: Allow
            Action: [ "s3:GetObject", "s3:PutObject", "s3:ListBucket" ]
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
              - !Sub "arn:aws:s3:::${S3BucketName}/*"

  LabUser:
    Condition: DoCreateUser
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AWS::StackName}-user"
      Path: "/"
      ManagedPolicyArns:
        - !If [HasBucket, !Ref S3RWPolicy, !Ref "AWS::NoValue"]

  LabUserAccessKey:
    Condition: DoCreateKey
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LabUser

Outputs:
  ProgrammaticUser:
    Value: !If [ DoCreateUser, !Ref LabUser, "not-created" ]
  AccessKeyId:
    Value: !If [ DoCreateKey, !Ref LabUserAccessKey, "not-created" ]
  SecretAccessKey:
    Value: !If [ DoCreateKey, !GetAtt LabUserAccessKey.SecretAccessKey, "not-created" ]
